---
application:
  name: "reactshop"
  project: "gatsby"
  organization: "QoveryCommunity"
  port: 3000
routers:
- name: "main-reactshop"
  routes:
  - application_name: "reactshop"
    paths:
    - "/*"
